spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler_app
    username: ${USER}
    password: PassWord@123
    driver-class-name: om.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: quartz-demo-app
          jobStore:
            useProperties: true
            isClustered: true
            clusterCheckinInterval: 5000
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            dataSource: quartzDataSource
            misfireThreshold: 60000
          dataSource:
            quartzDataSource:
              driver: om.mysql.cj.jdbc.Driver
              URL: jdbc:mysql://localhost:3306/scheduler_app
              user: ${USER}
              password: PassWord@123
          plugin:
            shutdownHook:
              class: org.quartz.plugins.management.ShutdownHookPlugin
              cleanShutdown: true